services:
  nginx:
    image: nginx:1.13-alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - erp-web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - roy-brains-erp-net

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email {email-address} -d {domain.com} --agree-tos
      
  erp-web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: erp-docker
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - DB_URL=${DB_URL}
      - DB_PASS=${DB_PASS}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
      - AWS_S3_REGION_NAME=${AWS_S3_REGION_NAME}
      - AWS_S3_SIGNATURE_VERSION=${AWS_S3_SIGNATURE_VERSION}
      - AWS_QUERYSTRING_EXPIRE=${AWS_QUERYSTRING_EXPIRE}
      - AWS_S3_CUSTOM_DOMAIN=${AWS_S3_CUSTOM_DOMAIN}
      - AWS_LOCATION=${AWS_LOCATION}

    volumes:
      - .:/app
    command: >
      sh -c "python manage.py collectstatic --noinput && python manage.py makemigrations && python manage.py migrate && gunicorn --bind 0.0.0.0:8000 core.wsgi:application"

    networks:
      - roy-brains-erp-net


networks:
  roy-brains-erp-net:
    driver: bridge